### ISSUE TITLE
dd iso to usb does not work

### ISSUE THREAD

**Issue by JoshRagem** [hvanderlaan/ubuntu-unattended#3]
When I dd the iso to a use drive, i end up with a drive that has no readable partition table.

**Comment by hvanderlaan** [comment]
This is correct when you dd a iso from ubuntu you well get the same issue.
If you whant to create a UBS use the "startup disk creator" in ubuntu itself.

**Comment by JoshRagem** [comment]
it is actually not true that this issue happens with iso from ubuntu. That is my usual method of prepping usb sticks for installs. It works every time.
