### ISSUE TITLE
Download URLs seem outdated.

### ISSUE THREAD

**Issue by tommyvdv** [hvanderlaan/ubuntu-unattended#8]
I believe the download URLs are outdated.

If you want I can relate a pull request to this issue suggesting a fix.

Thanks for putting this up 👍 . Should be a big help once I manage to get it working.

**Comment by hvanderlaan** [comment]
Please do create a pull request.

**Comment by hvanderlaan** [comment]
done, bumb version to 16.04.3 and 14.04.5
